name: default
kind: pipeline

steps:
  - name: build
    image: node:alpine
    commands:
      - yarn install --ignore-optional
      - yarn build
  - name: test
    image: node:alpine
    failure: ignore
    commands:
      - yarn coverage
  - name: deploy
    image: alpacadb/docker-lftp
    failure: ignore
    environment:
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
    commands:
      - cd frontend/public
      - lftp -e "set sftp:auto-confirm true; set ftp:ssl-force true; set xfer:timeout 10000; debug 3; open -u $FTP_USERNAME,$FTP_PASSWORD sftp://ssh.jim-fx.com:2221; mkdir -p share/plant; cd share/plant; mirror -p --scan-all-first --overwrite --verbose -R --skip-noaccess; quit;"
