name: default
kind: pipeline

clone:
  disable: true

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - .
  - name: clone
    image: alpine/git
    commands:
      - "[ ! -d '.git' ] && git clone --depth 1 --progress $DRONE_REMOTE_URL ."
      - git fetch --depth 1 --progress
      - git reset --hard origin/main
  - name: test
    image: node:alpine
    commands:
      - rm -rf coverage
      - npm i -g pnpm
      - pnpm coverage
      - mv coverage frontend/dist/coverage
  - name: build
    image: node:alpine
    commands:
      - npm i -g pnpm
      - pnpm install
      - pnpm build
  - name: coverage-publish
    image: plugins/codecov
    failure: ignore
    settings:
      name: plantarium
      token:
        from_secret: CODECOV_TOKEN
      paths:
        - frontend/public/coverage
    depends_on:
      - test
  - name: deploy
    image: alpacadb/docker-lftp
    when:
      branch: main
    environment:
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
    commands:
      - cp -r packages/geometry/public frontend/dist/geometry
      - cd frontend/dist
      - lftp -e "set sftp:auto-confirm true; set ftp:ssl-force true; set xfer:timeout 10000; debug 3; open -u $FTP_USERNAME,$FTP_PASSWORD sftp://ssh.jim-fx.com:2221; mkdir -p share/plant; cd share/plant; mirror -p --scan-all-first --overwrite --verbose -R --skip-noaccess; quit;"
    depends_on:
      - test
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - .
volumes:
  - name: cache
    host:
      path: /tmp/cache
