image: node:alpine

variables:
  YARN_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/.yarn'
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules
    - cache

stages:
  - build
  - test
  - deploy

build:frontend:
  stage: build
  script:
    - yarn install --ignore-optional
    - yarn build
  artifacts:
    paths:
      - frontend/public/build

test:
  stage: test
  script:
    - yarn coverage
    - node bin/combine_coverage
  artifacts:
    paths:
      - frontend/.nyc_output
      - backend/.nyc_output
      - packages/*/.nyc_output
      - coverage

pages:
  stage: deploy
  script:
    - mv frontend/public public
  artifacts:
    paths:
      - public
  only:
    - main
