image: node:alpine

variables:
  YARN_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/.yarn'
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules
    - cache

stages:
  - build
  - deploy

build:frontend:
  stage: build
  script:
    - yarn install --ignore-optional
    - yarn build
  artifacts:
    paths:
      - frontend/public/build

pages:
  stage: deploy
  script:
    - mv frontend/public public
  artifacts:
    paths:
      - public
  only:
    - main
