language: node_js
node_js:
  - "12"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - mkdir build
  - ls
  - npm run build
  - ls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/*
  on:
    branch: master
