apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: PNPM_REGISTRY
              value: https://registry.npmjs.org
            - name: PORT
              value: "8081"
          image: ghcr.io/jim-fx/plantarium-backend
          name: backend
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
