version: "3.4"
services:
  backend:
    image: ghcr.io/jim-fx/plantarium-backend
    network_mode: host
    ports:
      - 8081:8081
    environment:
      PORT: 8081
      PNPM_REGISTRY: "https://registry.npmjs.org"
    build:
      context: ./
      network: host
      dockerfile: ./backend/Dockerfile
